using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BigQuery.Linq
{
    [TableName("[githubarchive:github.timeline]")]
    public class github_timeline
    {
        public string repository_url { get; set; }
        public bool? repository_has_downloads { get; set; }
        public string repository_created_at { get; set; }
        public bool? repository_has_issues { get; set; }
        public string repository_description { get; set; }
        public long? repository_forks { get; set; }
        public string repository_fork { get; set; }
        public bool? repository_has_wiki { get; set; }
        public string repository_homepage { get; set; }
        public long? repository_size { get; set; }
        public string repository_private { get; set; }
        public string repository_name { get; set; }
        public string repository_owner { get; set; }
        public long? repository_open_issues { get; set; }
        public long? repository_watchers { get; set; }
        public string repository_pushed_at { get; set; }
        public string repository_language { get; set; }
        public string repository_organization { get; set; }
        public string repository_integrate_branch { get; set; }
        public string repository_master_branch { get; set; }
        public string actor_attributes_gravatar_id { get; set; }
        public string actor_attributes_type { get; set; }
        public string actor_attributes_login { get; set; }
        public string actor_attributes_name { get; set; }
        public string actor_attributes_company { get; set; }
        public string actor_attributes_location { get; set; }
        public string actor_attributes_blog { get; set; }
        public string actor_attributes_email { get; set; }
        public string created_at { get; set; }
        public bool? @public { get; set; }
        public string actor { get; set; }
        public string payload_head { get; set; }
        public long? payload_size { get; set; }
        public string payload_ref { get; set; }
        public string payload_master_branch { get; set; }
        public string payload_ref_type { get; set; }
        public string payload_description { get; set; }
        public long? payload_number { get; set; }
        public string payload_pull_request_head_label { get; set; }
        public string payload_pull_request_head_repo_name { get; set; }
        public string payload_pull_request_head_repo_master_branch { get; set; }
        public long? payload_pull_request_head_repo_size { get; set; }
        public string payload_pull_request_head_repo_created_at { get; set; }
        public string payload_pull_request_head_repo_has_wiki { get; set; }
        public string payload_pull_request_head_repo_clone_url { get; set; }
        public string payload_pull_request_head_repo_private { get; set; }
        public string payload_pull_request_head_repo_updated_at { get; set; }
        public long? payload_pull_request_head_repo_watchers { get; set; }
        public string payload_pull_request_head_repo_language { get; set; }
        public string payload_pull_request_head_repo_ssh_url { get; set; }
        public bool? payload_pull_request_head_repo_fork { get; set; }
        public string payload_pull_request_head_repo_url { get; set; }
        public string payload_pull_request_head_repo_git_url { get; set; }
        public long? payload_pull_request_head_repo_id { get; set; }
        public string payload_pull_request_head_repo_pushed_at { get; set; }
        public string payload_pull_request_head_repo_svn_url { get; set; }
        public long? payload_pull_request_head_repo_open_issues { get; set; }
        public string payload_pull_request_head_repo_mirror_url { get; set; }
        public bool? payload_pull_request_head_repo_has_downloads { get; set; }
        public string payload_pull_request_head_repo_homepage { get; set; }
        public string payload_pull_request_head_repo_has_issues { get; set; }
        public long? payload_pull_request_head_repo_forks { get; set; }
        public string payload_pull_request_head_repo_description { get; set; }
        public string payload_pull_request_head_repo_html_url { get; set; }
        public string payload_pull_request_head_repo_owner_avatar_url { get; set; }
        public string payload_pull_request_head_repo_owner_gravatar_id { get; set; }
        public string payload_pull_request_head_repo_owner_url { get; set; }
        public long? payload_pull_request_head_repo_owner_id { get; set; }
        public string payload_pull_request_head_repo_owner_login { get; set; }
        public string payload_pull_request_head_sha { get; set; }
        public string payload_pull_request_head_ref { get; set; }
        public string payload_pull_request_head_user_avatar_url { get; set; }
        public string payload_pull_request_head_user_gravatar_id { get; set; }
        public string payload_pull_request_head_user_url { get; set; }
        public long? payload_pull_request_head_user_id { get; set; }
        public string payload_pull_request_head_user_login { get; set; }
        public string payload_pull_request_issue_url { get; set; }
        public long? payload_pull_request_number { get; set; }
        public long? payload_pull_request_changed_files { get; set; }
        public string payload_pull_request_merged_by { get; set; }
        public string payload_pull_request_merged_by_gravatar_id { get; set; }
        public string payload_pull_request_merged_by_avatar_url { get; set; }
        public string payload_pull_request_merged_by_url { get; set; }
        public long? payload_pull_request_merged_by_id { get; set; }
        public string payload_pull_request_merged_by_login { get; set; }
        public string payload_pull_request_created_at { get; set; }
        public string payload_pull_request_merged { get; set; }
        public long? payload_pull_request_comments { get; set; }
        public string payload_pull_request_body { get; set; }
        public string payload_pull_request_title { get; set; }
        public long? payload_pull_request_additions { get; set; }
        public string payload_pull_request_diff_url { get; set; }
        public string payload_pull_request_updated_at { get; set; }
        public string payload_pull_request__links_html_href { get; set; }
        public string payload_pull_request__links_self_href { get; set; }
        public string payload_pull_request__links_comments_href { get; set; }
        public string payload_pull_request__links_review_comments_href { get; set; }
        public string payload_pull_request_url { get; set; }
        public long? payload_pull_request_id { get; set; }
        public string payload_pull_request_patch_url { get; set; }
        public string payload_pull_request_mergeable { get; set; }
        public string payload_pull_request_merged_at { get; set; }
        public string payload_pull_request_closed_at { get; set; }
        public long? payload_pull_request_commits { get; set; }
        public string payload_pull_request_user_avatar_url { get; set; }
        public string payload_pull_request_user_gravatar_id { get; set; }
        public string payload_pull_request_user_url { get; set; }
        public long? payload_pull_request_user_id { get; set; }
        public string payload_pull_request_user_login { get; set; }
        public string payload_pull_request_html_url { get; set; }
        public long? payload_pull_request_deletions { get; set; }
        public long? payload_pull_request_review_comments { get; set; }
        public string payload_pull_request_state { get; set; }
        public string payload_pull_request_base_label { get; set; }
        public string payload_pull_request_base_repo_name { get; set; }
        public string payload_pull_request_base_repo_master_branch { get; set; }
        public long? payload_pull_request_base_repo_size { get; set; }
        public string payload_pull_request_base_repo_created_at { get; set; }
        public string payload_pull_request_base_repo_has_wiki { get; set; }
        public string payload_pull_request_base_repo_clone_url { get; set; }
        public string payload_pull_request_base_repo_private { get; set; }
        public string payload_pull_request_base_repo_updated_at { get; set; }
        public long? payload_pull_request_base_repo_watchers { get; set; }
        public string payload_pull_request_base_repo_language { get; set; }
        public string payload_pull_request_base_repo_ssh_url { get; set; }
        public string payload_pull_request_base_repo_fork { get; set; }
        public string payload_pull_request_base_repo_url { get; set; }
        public string payload_pull_request_base_repo_git_url { get; set; }
        public long? payload_pull_request_base_repo_id { get; set; }
        public string payload_pull_request_base_repo_pushed_at { get; set; }
        public string payload_pull_request_base_repo_svn_url { get; set; }
        public long? payload_pull_request_base_repo_open_issues { get; set; }
        public string payload_pull_request_base_repo_mirror_url { get; set; }
        public bool? payload_pull_request_base_repo_has_downloads { get; set; }
        public string payload_pull_request_base_repo_homepage { get; set; }
        public string payload_pull_request_base_repo_has_issues { get; set; }
        public long? payload_pull_request_base_repo_forks { get; set; }
        public string payload_pull_request_base_repo_description { get; set; }
        public string payload_pull_request_base_repo_html_url { get; set; }
        public string payload_pull_request_base_repo_owner_avatar_url { get; set; }
        public string payload_pull_request_base_repo_owner_gravatar_id { get; set; }
        public string payload_pull_request_base_repo_owner_url { get; set; }
        public long? payload_pull_request_base_repo_owner_id { get; set; }
        public string payload_pull_request_base_repo_owner_login { get; set; }
        public string payload_pull_request_base_sha { get; set; }
        public string payload_pull_request_base_ref { get; set; }
        public string payload_pull_request_base_user_avatar_url { get; set; }
        public string payload_pull_request_base_user_gravatar_id { get; set; }
        public string payload_pull_request_base_user_url { get; set; }
        public long? payload_pull_request_base_user_id { get; set; }
        public string payload_pull_request_base_user_login { get; set; }
        public string payload_action { get; set; }
        public long? payload_issue { get; set; }
        public long? payload_issue_id { get; set; }
        public long? payload_comment_id { get; set; }
        public string payload_name { get; set; }
        public string payload_url { get; set; }
        public long? payload_id { get; set; }
        public string payload_desc { get; set; }
        public string payload_member_avatar_url { get; set; }
        public string payload_member_gravatar_id { get; set; }
        public string payload_member_url { get; set; }
        public long? payload_member_id { get; set; }
        public string payload_member_login { get; set; }
        public string payload_commit { get; set; }
        public string payload_target_gravatar_id { get; set; }
        public long? payload_target_followers { get; set; }
        public long? payload_target_id { get; set; }
        public long? payload_target_repos { get; set; }
        public string payload_target_login { get; set; }
        public string payload_comment_commit_id { get; set; }
        public string payload_comment_updated_at { get; set; }
        public string payload_comment_created_at { get; set; }
        public string payload_comment_path { get; set; }
        public long? payload_comment_user_id { get; set; }
        public string payload_comment_user_avatar_url { get; set; }
        public string payload_comment_user_url { get; set; }
        public string payload_comment_user_login { get; set; }
        public string payload_comment_user_gravatar_id { get; set; }
        public long? payload_comment_position { get; set; }
        public string payload_comment_url { get; set; }
        public string payload_comment_body { get; set; }
        public string payload_comment_original_commit_id { get; set; }
        public long? payload_comment_original_position { get; set; }
        public string payload_after { get; set; }
        public string payload_before { get; set; }
        public string payload_commit_id { get; set; }
        public string payload_commit_email { get; set; }
        public string payload_commit_msg { get; set; }
        public string payload_commit_name { get; set; }
        public string payload_commit_flag { get; set; }
        public string payload_page_sha { get; set; }
        public string payload_page_title { get; set; }
        public string payload_page_action { get; set; }
        public string payload_page_page_name { get; set; }
        public string payload_page_summary { get; set; }
        public string payload_page_html_url { get; set; }
        public string url { get; set; }
        public string type { get; set; }
    }
}
